lxc-to-lxd: Make sure we're root
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

diff --git a/snapcraft/commands/lxc-to-lxd b/snapcraft/commands/lxc-to-lxd
--- a/snapcraft/commands/lxc-to-lxd
+++ b/snapcraft/commands/lxc-to-lxd
@@ -6,6 +6,12 @@ if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" !=
     exec aa-exec -p unconfined -- "$0" "$@"
 fi
 
+# Check that we're root
+if [ "$(id -u)" != "0" ]; then
+    echo "error: This tool must be run as root."
+    exit 1
+fi
+
 export SNAP_CURRENT="$(realpath "${SNAP}/..")/current"
 export LXD_DIR=${LXD_DIR:-"${SNAP_COMMON}/lxd/"}
 
